kind: Simple
apiVersion: k3d.io/v1alpha4
metadata:
  name: main
agents: 3
servers: 1
kubeAPI:
  hostPort: "6443"
network: k3d-main-network
ports:
- port: "8080:80"
  nodeFilters:
  - loadbalancer
- port: "8443:443"
  nodeFilters:
  - loadbalancer
