kind: Simple
apiVersion: k3d.io/v1alpha4
metadata:
  name: main
agents: 2
servers: 1
kubeAPI:
  hostIP: "127.0.0.1"
  hostPort: "6443"
network: k3d-main-network
options:
  k3s:
    extraArgs:
    - arg: "--flannel-backend=none"
      nodeFilters:
      - server:*
ports:
- port: "8080:80"
  nodeFilters:
  - loadbalancer
- port: "8443:443"
  nodeFilters:
  - loadbalancer
volumes:
- volume: "C:\\Users\\Brian\\Development\\Kubernetes-Cluster\\Calico\\Manifest.yaml:/var/lib/rancher/k3s/server/manifests/calico.yaml"
  nodeFilters:
  - server:*
