kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: grafana
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`grafana.localhost`)
    services:
    - kind: Service
      name: grafana
      port: 80
