kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: argo
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`argo.localhost`)
    services:
    - kind: Service
      name: argo-argocd-server
      port: 80
